-- Caché persistente de Chile RUT Empresa.
-- Ejecutar una vez en Supabase SQL Editor.

BEGIN;

CREATE TABLE IF NOT EXISTS empresa (
    id_empresa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut VARCHAR(12) NOT NULL UNIQUE,
    dv CHAR(1),
    razon_social VARCHAR(255) NOT NULL,
    fecha_inicio_actividades VARCHAR(10),
    giro TEXT,
    rubro VARCHAR(255),
    subrubro VARCHAR(255),
    categoria_tributaria VARCHAR(20),
    afecta_iva CHAR(1),
    actividades JSONB NOT NULL DEFAULT '[]'::JSONB,
    comuna VARCHAR(100),
    region VARCHAR(150),
    num_trabajadores INTEGER,
    fuente VARCHAR(100) NOT NULL DEFAULT 'Chile RUT Empresa',
    consultado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_empresa_actividades_array
        CHECK (jsonb_typeof(actividades) = 'array')
);

CREATE INDEX IF NOT EXISTS idx_empresa_consultado_en ON empresa (consultado_en);

CREATE OR REPLACE FUNCTION fn_obtener_empresa_cache(p_rut VARCHAR)
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT jsonb_build_object(
        'found', TRUE,
        'rut', e.rut,
        'dv', e.dv,
        'razon_social', e.razon_social,
        'fecha_inicio_actividades', e.fecha_inicio_actividades,
        'giro', e.giro,
        'rubro', e.rubro,
        'subrubro', e.subrubro,
        'categoria_tributaria', e.categoria_tributaria,
        'afecta_iva', e.afecta_iva,
        'actividades', e.actividades,
        'comuna', e.comuna,
        'region', e.region,
        'num_trabajadores', e.num_trabajadores::TEXT,
        'fuente', e.fuente,
        'consultado_en', e.consultado_en,
        'cache_vigente', e.consultado_en >= NOW() - INTERVAL '30 days'
    )
    FROM empresa e
    WHERE e.rut = p_rut;
$$;

CREATE OR REPLACE FUNCTION fn_guardar_empresa_cache(p_datos JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_empresa empresa%ROWTYPE;
BEGIN
    INSERT INTO empresa (
        rut, dv, razon_social, fecha_inicio_actividades, giro, rubro,
        subrubro, categoria_tributaria, afecta_iva, actividades,
        comuna, region, num_trabajadores, fuente, consultado_en
    ) VALUES (
        p_datos->>'rut',
        p_datos->>'dv',
        p_datos->>'razon_social',
        p_datos->>'fecha_inicio_actividades',
        p_datos->>'giro',
        p_datos->>'rubro',
        p_datos->>'subrubro',
        p_datos->>'categoria_tributaria',
        p_datos->>'afecta_iva',
        COALESCE(p_datos->'actividades', '[]'::JSONB),
        p_datos->>'comuna',
        p_datos->>'region',
        NULLIF(p_datos->>'num_trabajadores', '')::INTEGER,
        COALESCE(p_datos->>'fuente', 'Chile RUT Empresa'),
        NOW()
    )
    ON CONFLICT (rut) DO UPDATE SET
        dv = EXCLUDED.dv,
        razon_social = EXCLUDED.razon_social,
        fecha_inicio_actividades = EXCLUDED.fecha_inicio_actividades,
        giro = EXCLUDED.giro,
        rubro = EXCLUDED.rubro,
        subrubro = EXCLUDED.subrubro,
        categoria_tributaria = EXCLUDED.categoria_tributaria,
        afecta_iva = EXCLUDED.afecta_iva,
        actividades = EXCLUDED.actividades,
        comuna = EXCLUDED.comuna,
        region = EXCLUDED.region,
        num_trabajadores = EXCLUDED.num_trabajadores,
        fuente = EXCLUDED.fuente,
        consultado_en = NOW(),
        fecha_actualizacion = NOW()
    RETURNING * INTO v_empresa;

    RETURN fn_obtener_empresa_cache(v_empresa.rut);
END;
$$;

ALTER TABLE empresa ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON FUNCTION fn_obtener_empresa_cache(VARCHAR) FROM PUBLIC;
REVOKE ALL ON FUNCTION fn_guardar_empresa_cache(JSONB) FROM PUBLIC;

COMMIT;
