-- =============================================================
-- PRACTICALINK - ESQUEMA POSTGRESQL / SUPABASE
-- Reconstruido desde el catalogo de la base de datos (2026-08-30).
-- Ejecutar sobre una base vacia. Este archivo no elimina objetos ni datos.
-- =============================================================

BEGIN;

CREATE TABLE rol (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE usuario_rol (
    id_usuario BIGINT NOT NULL,
    id_rol BIGINT NOT NULL,
    PRIMARY KEY (id_usuario, id_rol),
    CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_usuario_rol_rol FOREIGN KEY (id_rol)
        REFERENCES rol (id_rol) ON DELETE RESTRICT
);

CREATE TABLE estudiante (
    id_estudiante BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL UNIQUE,
    rut VARCHAR(12) NOT NULL UNIQUE,
    carrera VARCHAR(150) NOT NULL,
    sede VARCHAR(100) NOT NULL,
    telefono VARCHAR(20),
    direccion VARCHAR(255),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_estudiante_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE CASCADE
);

CREATE TABLE centro_practica (
    id_centro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    rut_empresa VARCHAR(12) UNIQUE,
    direccion VARCHAR(255),
    telefono VARCHAR(20),
    correo VARCHAR(150),
    contacto_nombre VARCHAR(100),
    contacto_cargo VARCHAR(100),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE estado_practica (
    id_estado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    es_final BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE practica (
    id_practica BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estudiante BIGINT NOT NULL,
    id_centro BIGINT NOT NULL,
    id_estado_actual BIGINT NOT NULL,
    fecha_inicio DATE,
    fecha_termino DATE,
    horas INTEGER,
    cargo_funcion VARCHAR(150),
    descripcion TEXT,
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_practica_estudiante FOREIGN KEY (id_estudiante)
        REFERENCES estudiante (id_estudiante) ON DELETE RESTRICT,
    CONSTRAINT fk_practica_centro FOREIGN KEY (id_centro)
        REFERENCES centro_practica (id_centro) ON DELETE RESTRICT,
    CONSTRAINT fk_practica_estado FOREIGN KEY (id_estado_actual)
        REFERENCES estado_practica (id_estado) ON DELETE RESTRICT,
    CONSTRAINT chk_practica_fechas CHECK (
        fecha_termino IS NULL OR fecha_inicio IS NULL OR fecha_termino >= fecha_inicio
    ),
    CONSTRAINT chk_practica_horas CHECK (horas IS NULL OR horas > 0)
);

CREATE TABLE historial_estado (
    id_historial BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_practica BIGINT NOT NULL,
    id_estado BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    fecha_cambio TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    observacion VARCHAR(500),
    CONSTRAINT fk_historial_practica FOREIGN KEY (id_practica)
        REFERENCES practica (id_practica) ON DELETE CASCADE,
    CONSTRAINT fk_historial_estado FOREIGN KEY (id_estado)
        REFERENCES estado_practica (id_estado) ON DELETE RESTRICT,
    CONSTRAINT fk_historial_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE RESTRICT
);

CREATE TABLE seguimiento (
    id_seguimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_practica BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    tipo VARCHAR(50),
    observacion TEXT NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_seguimiento_practica FOREIGN KEY (id_practica)
        REFERENCES practica (id_practica) ON DELETE CASCADE,
    CONSTRAINT fk_seguimiento_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE RESTRICT
);

CREATE TABLE incidencia (
    id_incidencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_practica BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    descripcion TEXT NOT NULL,
    prioridad VARCHAR(20) NOT NULL DEFAULT 'MEDIA',
    estado VARCHAR(20) NOT NULL DEFAULT 'ABIERTA',
    fecha_resolucion TIMESTAMPTZ,
    CONSTRAINT fk_incidencia_practica FOREIGN KEY (id_practica)
        REFERENCES practica (id_practica) ON DELETE CASCADE,
    CONSTRAINT fk_incidencia_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE RESTRICT,
    CONSTRAINT chk_incidencia_prioridad CHECK (
        prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')
    ),
    CONSTRAINT chk_incidencia_estado CHECK (
        estado IN ('ABIERTA', 'EN_REVISION', 'RESUELTA', 'CERRADA')
    )
);

CREATE TABLE alerta (
    id_alerta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_incidencia BIGINT NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    mensaje VARCHAR(500) NOT NULL,
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT fk_alerta_incidencia FOREIGN KEY (id_incidencia)
        REFERENCES incidencia (id_incidencia) ON DELETE CASCADE,
    CONSTRAINT chk_alerta_estado CHECK (
        estado IN ('PENDIENTE', 'LEIDA', 'CERRADA')
    )
);

CREATE TABLE tipo_documento (
    id_tipo_documento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE documento (
    id_documento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_practica BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    id_tipo_documento BIGINT NOT NULL,
    nombre_original VARCHAR(255) NOT NULL,
    nombre_almacenado VARCHAR(255) NOT NULL,
    ruta_archivo VARCHAR(500) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    tamano_bytes BIGINT,
    fecha_subida TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_documento_practica FOREIGN KEY (id_practica)
        REFERENCES practica (id_practica) ON DELETE CASCADE,
    CONSTRAINT fk_documento_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE RESTRICT,
    CONSTRAINT fk_documento_tipo FOREIGN KEY (id_tipo_documento)
        REFERENCES tipo_documento (id_tipo_documento) ON DELETE RESTRICT,
    CONSTRAINT chk_documento_tamano CHECK (
        tamano_bytes IS NULL OR tamano_bytes > 0
    )
);

CREATE TABLE cierre_practica (
    id_cierre BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_practica BIGINT NOT NULL UNIQUE,
    id_usuario BIGINT NOT NULL,
    fecha_cierre TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resultado VARCHAR(30) NOT NULL,
    observacion TEXT,
    CONSTRAINT fk_cierre_practica FOREIGN KEY (id_practica)
        REFERENCES practica (id_practica) ON DELETE RESTRICT,
    CONSTRAINT fk_cierre_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE RESTRICT,
    CONSTRAINT chk_cierre_resultado CHECK (
        resultado IN ('APROBADA', 'REPROBADA', 'ANULADA')
    )
);

-- Catalogos iniciales necesarios para operar la aplicacion.
INSERT INTO rol (nombre, descripcion) VALUES
    ('ESTUDIANTE', 'Estudiante que realiza una práctica profesional'),
    ('GESTOR', 'Usuario encargado de gestionar y realizar seguimiento de prácticas'),
    ('ADMINISTRADOR', 'Usuario con permisos de administración del sistema');

INSERT INTO estado_practica (nombre, descripcion, es_final) VALUES
    ('REGISTRADA', 'La práctica fue registrada por el estudiante', FALSE),
    ('EN_REVISION', 'La práctica está siendo revisada', FALSE),
    ('OBSERVADA', 'La práctica requiere correcciones o información adicional', FALSE),
    ('APROBADA', 'La práctica fue aprobada para iniciar o continuar el proceso', FALSE),
    ('EN_CURSO', 'La práctica se encuentra actualmente en desarrollo', FALSE),
    ('FINALIZADA', 'La práctica fue finalizada correctamente', TRUE),
    ('RECHAZADA', 'La práctica fue rechazada', TRUE);

INSERT INTO tipo_documento (nombre, descripcion) VALUES
    ('CONTRATO', 'Contrato o convenio asociado a la práctica'),
    ('FORMULARIO', 'Formulario requerido durante el proceso'),
    ('CARTA', 'Carta o documento formal relacionado con la práctica'),
    ('SEGUIMIENTO', 'Documento asociado a un seguimiento'),
    ('CIERRE', 'Documento asociado al cierre de la práctica'),
    ('OTRO', 'Otro documento relacionado con la práctica');

-- Funcion consumida por GET /auth/context.
CREATE OR REPLACE FUNCTION fn_registrar_usuario_estudiante(
    p_datos JSONB,
    p_password_hash VARCHAR
)
RETURNS JSONB
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    v_id_usuario BIGINT;
    v_id_estudiante BIGINT;
    v_id_rol BIGINT;
    v_correo VARCHAR(150);
    v_rut VARCHAR(12);
BEGIN
    v_correo := LOWER(BTRIM(p_datos ->> 'correo'));
    v_rut := BTRIM(p_datos ->> 'rut');

    IF EXISTS (
        SELECT 1 FROM usuario u WHERE LOWER(u.correo) = v_correo
    ) THEN
        RETURN jsonb_build_object('error', 'CORREO_EXISTENTE');
    END IF;

    IF EXISTS (
        SELECT 1 FROM estudiante e WHERE UPPER(e.rut) = UPPER(v_rut)
    ) THEN
        RETURN jsonb_build_object('error', 'RUT_EXISTENTE');
    END IF;

    SELECT id_rol INTO v_id_rol
    FROM rol
    WHERE nombre = 'ESTUDIANTE' AND activo = TRUE
    LIMIT 1;

    IF v_id_rol IS NULL THEN
        RETURN jsonb_build_object(
            'error', 'ROL_ESTUDIANTE_NO_CONFIGURADO'
        );
    END IF;

    INSERT INTO usuario (
        nombre, apellido, correo, password_hash
    ) VALUES (
        BTRIM(p_datos ->> 'nombre'),
        BTRIM(p_datos ->> 'apellido'),
        v_correo,
        p_password_hash
    )
    RETURNING id_usuario INTO v_id_usuario;

    INSERT INTO usuario_rol (id_usuario, id_rol)
    VALUES (v_id_usuario, v_id_rol);

    INSERT INTO estudiante (
        id_usuario, rut, carrera, sede
    ) VALUES (
        v_id_usuario,
        v_rut,
        BTRIM(p_datos ->> 'carrera'),
        BTRIM(p_datos ->> 'sede')
    )
    RETURNING id_estudiante INTO v_id_estudiante;

    RETURN jsonb_build_object(
        'id_usuario', v_id_usuario,
        'id_estudiante', v_id_estudiante,
        'nombre', BTRIM(p_datos ->> 'nombre'),
        'apellido', BTRIM(p_datos ->> 'apellido'),
        'correo', v_correo,
        'rol', 'ESTUDIANTE'
    );
END;
$$;

CREATE OR REPLACE FUNCTION fn_contexto_usuario(p_id_usuario BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_contexto JSONB;
BEGIN
    SELECT jsonb_build_object(
        'usuario', jsonb_build_object(
            'id_usuario', u.id_usuario,
            'nombre', u.nombre,
            'apellido', u.apellido,
            'correo', u.correo
        ),
        'roles', COALESCE((
            SELECT jsonb_agg(r.nombre ORDER BY r.nombre)
            FROM usuario_rol ur
            JOIN rol r ON r.id_rol = ur.id_rol
            WHERE ur.id_usuario = u.id_usuario
              AND r.activo = TRUE
        ), '[]'::jsonb),
        'perfil', CASE
            WHEN e.id_estudiante IS NOT NULL THEN jsonb_build_object(
                'id_estudiante', e.id_estudiante,
                'rut', e.rut,
                'carrera', e.carrera,
                'sede', e.sede
            )
            ELSE NULL
        END,
        'practica_actual', CASE
            WHEN p.id_practica IS NOT NULL THEN jsonb_build_object(
                'id_practica', p.id_practica,
                'estado', jsonb_build_object(
                    'id_estado', ep.id_estado,
                    'nombre', ep.nombre,
                    'es_final', ep.es_final
                ),
                'centro_practica', jsonb_build_object(
                    'id_centro', cp.id_centro,
                    'nombre', cp.nombre
                ),
                'fecha_inicio', p.fecha_inicio,
                'fecha_termino', p.fecha_termino,
                'horas', p.horas,
                'cargo_funcion', p.cargo_funcion
            )
            ELSE NULL
        END
    )
    INTO v_contexto
    FROM usuario u
    LEFT JOIN estudiante e ON e.id_usuario = u.id_usuario
    LEFT JOIN LATERAL (
        SELECT pr.*
        FROM practica pr
        WHERE pr.id_estudiante = e.id_estudiante
        ORDER BY
            CASE
                WHEN EXISTS (
                    SELECT 1
                    FROM estado_practica est
                    WHERE est.id_estado = pr.id_estado_actual
                      AND est.es_final = FALSE
                ) THEN 0
                ELSE 1
            END,
            pr.fecha_registro DESC
        LIMIT 1
    ) p ON TRUE
    LEFT JOIN estado_practica ep ON ep.id_estado = p.id_estado_actual
    LEFT JOIN centro_practica cp ON cp.id_centro = p.id_centro
    WHERE u.id_usuario = p_id_usuario
      AND u.activo = TRUE;

    RETURN v_contexto;
END;
$$;

-- Registra centro, practica e historial en una unica transaccion. El bloqueo
-- del perfil evita dos registros activos concurrentes para el mismo estudiante.
CREATE OR REPLACE FUNCTION fn_registrar_practica(
    p_id_usuario BIGINT,
    p_datos JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    v_id_estudiante BIGINT;
    v_id_estado BIGINT;
    v_nombre_estado VARCHAR(50);
    v_id_centro BIGINT;
    v_id_practica BIGINT;
    v_rut_empresa VARCHAR(12);
BEGIN
    SELECT e.id_estudiante
    INTO v_id_estudiante
    FROM estudiante e
    WHERE e.id_usuario = p_id_usuario
    FOR UPDATE;

    IF v_id_estudiante IS NULL THEN
        RETURN jsonb_build_object(
            'error', 'PERFIL_ESTUDIANTE_NO_ENCONTRADO'
        );
    END IF;

    IF EXISTS (
        SELECT 1
        FROM practica p
        JOIN estado_practica ep
          ON ep.id_estado = p.id_estado_actual
        WHERE p.id_estudiante = v_id_estudiante
          AND ep.es_final = FALSE
    ) THEN
        RETURN jsonb_build_object('error', 'PRACTICA_ACTIVA');
    END IF;

    SELECT ep.id_estado, ep.nombre
    INTO v_id_estado, v_nombre_estado
    FROM estado_practica ep
    WHERE ep.nombre = 'REGISTRADA'
      AND ep.activo = TRUE
    LIMIT 1;

    IF v_id_estado IS NULL THEN
        RETURN jsonb_build_object(
            'error', 'ESTADO_INICIAL_NO_ENCONTRADO'
        );
    END IF;

    v_rut_empresa := NULLIF(BTRIM(p_datos #>> '{centro,rut_empresa}'), '');

    IF v_rut_empresa IS NOT NULL THEN
        SELECT cp.id_centro
        INTO v_id_centro
        FROM centro_practica cp
        WHERE UPPER(cp.rut_empresa) = UPPER(v_rut_empresa)
        LIMIT 1;
    END IF;

    IF v_id_centro IS NULL THEN
        INSERT INTO centro_practica (
            nombre,
            rut_empresa,
            direccion,
            telefono,
            correo,
            contacto_nombre,
            contacto_cargo
        ) VALUES (
            BTRIM(p_datos #>> '{centro,nombre}'),
            v_rut_empresa,
            NULLIF(BTRIM(p_datos #>> '{centro,direccion}'), ''),
            NULLIF(BTRIM(p_datos #>> '{centro,telefono}'), ''),
            NULLIF(BTRIM(p_datos #>> '{centro,correo}'), ''),
            NULLIF(BTRIM(p_datos #>> '{centro,contacto_nombre}'), ''),
            NULLIF(BTRIM(p_datos #>> '{centro,contacto_cargo}'), '')
        )
        RETURNING id_centro INTO v_id_centro;
    END IF;

    INSERT INTO practica (
        id_estudiante,
        id_centro,
        id_estado_actual,
        fecha_inicio,
        fecha_termino,
        horas,
        cargo_funcion,
        descripcion
    ) VALUES (
        v_id_estudiante,
        v_id_centro,
        v_id_estado,
        NULLIF(p_datos ->> 'fecha_inicio', '')::DATE,
        NULLIF(p_datos ->> 'fecha_termino', '')::DATE,
        NULLIF(p_datos ->> 'horas', '')::INTEGER,
        NULLIF(BTRIM(p_datos ->> 'cargo_funcion'), ''),
        NULLIF(BTRIM(p_datos ->> 'descripcion'), '')
    )
    RETURNING id_practica INTO v_id_practica;

    INSERT INTO historial_estado (
        id_practica,
        id_estado,
        id_usuario,
        observacion
    ) VALUES (
        v_id_practica,
        v_id_estado,
        p_id_usuario,
        'Registro inicial de la práctica'
    );

    RETURN jsonb_build_object(
        'id_practica', v_id_practica,
        'id_centro', v_id_centro,
        'estado', v_nombre_estado,
        'mensaje', 'Práctica registrada correctamente'
    );
END;
$$;

CREATE OR REPLACE FUNCTION fn_completar_perfil_estudiante(
    p_id_usuario BIGINT,
    p_datos JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    v_id_estudiante BIGINT;
    v_rut VARCHAR(12);
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM usuario u
        JOIN usuario_rol ur ON ur.id_usuario = u.id_usuario
        JOIN rol r ON r.id_rol = ur.id_rol
        WHERE u.id_usuario = p_id_usuario
          AND u.activo = TRUE
          AND r.nombre = 'ESTUDIANTE'
          AND r.activo = TRUE
    ) THEN
        RETURN jsonb_build_object(
            'error', 'USUARIO_ESTUDIANTE_NO_VALIDO'
        );
    END IF;

    IF EXISTS (
        SELECT 1 FROM estudiante e
        WHERE e.id_usuario = p_id_usuario
    ) THEN
        RETURN jsonb_build_object('error', 'PERFIL_EXISTENTE');
    END IF;

    v_rut := BTRIM(p_datos ->> 'rut');

    IF EXISTS (
        SELECT 1 FROM estudiante e
        WHERE UPPER(e.rut) = UPPER(v_rut)
    ) THEN
        RETURN jsonb_build_object('error', 'RUT_EXISTENTE');
    END IF;

    INSERT INTO estudiante (
        id_usuario,
        rut,
        carrera,
        sede,
        telefono,
        direccion
    ) VALUES (
        p_id_usuario,
        v_rut,
        BTRIM(p_datos ->> 'carrera'),
        BTRIM(p_datos ->> 'sede'),
        NULLIF(BTRIM(p_datos ->> 'telefono'), ''),
        NULLIF(BTRIM(p_datos ->> 'direccion'), '')
    )
    RETURNING id_estudiante INTO v_id_estudiante;

    RETURN jsonb_build_object(
        'id_estudiante', v_id_estudiante,
        'mensaje', 'Perfil de estudiante completado correctamente'
    );
END;
$$;

CREATE OR REPLACE FUNCTION fn_revisar_practica(
    p_id_practica BIGINT,
    p_id_usuario BIGINT,
    p_decision VARCHAR,
    p_observacion VARCHAR DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    v_estado_actual VARCHAR(50);
    v_id_estado BIGINT;
BEGIN
    SELECT ep.nombre
    INTO v_estado_actual
    FROM practica p
    JOIN estado_practica ep ON ep.id_estado = p.id_estado_actual
    WHERE p.id_practica = p_id_practica
    FOR UPDATE OF p;

    IF v_estado_actual IS NULL THEN
        RETURN jsonb_build_object('error', 'SOLICITUD_NO_ENCONTRADA');
    END IF;

    IF v_estado_actual NOT IN ('REGISTRADA', 'EN_REVISION', 'OBSERVADA') THEN
        RETURN jsonb_build_object('error', 'SOLICITUD_NO_REVISABLE');
    END IF;

    SELECT id_estado INTO v_id_estado
    FROM estado_practica
    WHERE nombre = UPPER(p_decision) AND activo = TRUE;

    IF v_id_estado IS NULL OR UPPER(p_decision) NOT IN (
        'APROBADA', 'OBSERVADA', 'RECHAZADA'
    ) THEN
        RETURN jsonb_build_object('error', 'DECISION_INVALIDA');
    END IF;

    UPDATE practica
    SET id_estado_actual = v_id_estado,
        fecha_actualizacion = NOW()
    WHERE id_practica = p_id_practica;

    INSERT INTO historial_estado (
        id_practica, id_estado, id_usuario, observacion
    ) VALUES (
        p_id_practica, v_id_estado, p_id_usuario, NULLIF(BTRIM(p_observacion), '')
    );

    RETURN jsonb_build_object(
        'id_practica', p_id_practica,
        'estado', UPPER(p_decision),
        'mensaje', 'Solicitud revisada correctamente'
    );
END;
$$;

-- La base de origen tiene RLS habilitado, pero no posee politicas definidas.
-- El backend se conecta directamente a PostgreSQL; el acceso mediante la API
-- de Supabase permanecera bloqueado hasta que se creen politicas explicitas.
ALTER TABLE rol ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuario_rol ENABLE ROW LEVEL SECURITY;
ALTER TABLE estudiante ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_practica ENABLE ROW LEVEL SECURITY;
ALTER TABLE estado_practica ENABLE ROW LEVEL SECURITY;
ALTER TABLE practica ENABLE ROW LEVEL SECURITY;
ALTER TABLE historial_estado ENABLE ROW LEVEL SECURITY;
ALTER TABLE seguimiento ENABLE ROW LEVEL SECURITY;
ALTER TABLE incidencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerta ENABLE ROW LEVEL SECURITY;
ALTER TABLE tipo_documento ENABLE ROW LEVEL SECURITY;
ALTER TABLE documento ENABLE ROW LEVEL SECURITY;
ALTER TABLE cierre_practica ENABLE ROW LEVEL SECURITY;

-- No se replica public.rls_auto_enable(): es una funcion de administracion de
-- Supabase que requiere privilegios elevados y no pertenece al dominio de la
-- aplicacion. Las tablas anteriores ya conservan explicitamente su estado RLS.

COMMIT;
